spring:
  redis:
    database: 0
    port: 6379
    host:
    password:
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/awakeningera?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    sentinel:
      transport:
        dashboard:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: statement
    cache-enabled: true

